apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ozjul8osj-python
  janus-idp.io/tekton: ozjul8osj-python
  backstage.io/kubernetes-id: ozjul8osj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ozjul8osj-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
